language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
before_script: "cd test_api_server && bundle exec rackup &"
script: "bundle exec rspec && sleep 1"
